# Generated by Django 3.2.8 on 2022-01-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220103_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='t2',
            name='name1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.t1'),
        ),
    ]
